### ISSUE TITLE
FW downgrade question

### ISSUE THREAD

**Issue by josesilveiraa** [XiaomiFirmwareUpdater/mi-firmware-updater#37]
Hi. I'm on stock 12.5.x firmware, and I want to install ArrowOS, which requires 12.0.x firmware.

Could I do the proper wipes and then flash just 12.0.x firmware before the ROM? Or will it cause problems to my device?

**Comment by yshalsager** [comment]
It's fine, you can downgrade it without wipe if both firmware files are the same android version.
