### ISSUE TITLE
Mi 9T (Davinci) Firmware Update

### ISSUE THREAD

**Issue by reyis4402** [XiaomiFirmwareUpdater/mi-firmware-updater#46]
Hello, I have a Mi 9T (Davinci) phone. But I can't install most Firmware builds. If I install the latest Firmware builds it won't load any custom roms.

There was no such problem before. What did I break?

I'm using an old firmware build from 2020.

Sorry for the bad English.

**Comment by yshalsager** [comment]
You should use the firmware version suggested by your ROM developer. Some ROMs might not work with the latest firmware files without some modifications from the ROM developer.
