### ISSUE TITLE
Flashing only vendor partition on POCO M3

### ISSUE THREAD

**Issue by YusufKhan-improves-shit** [XiaomiFirmwareUpdater/mi-firmware-updater#47]
Hey!

I have a POCO M3 phone running Ubuntu Touch and I wish to downgrade my vendor partition. Ubuntu Touch pretty much is just the user partition, system partition, and boot partition so I want to downgrade everything else(that will still make my phone bootable) as my POCO M3 has features that do not appear in previous firmware versions that I do not like(eg. When turned off, when charging the phone will turn back on, show a battery indicator, then turn back off, this is in the miui style making it look even worse ;p).

**Comment by yshalsager** [comment]
You can use https://github.com/XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator to generate vendor package from a ROM, then feel free to remove boot.img from the zip and edit the updater-script or put ub boot image there.
