### ISSUE TITLE
Is it possible to include kernel?

### ISSUE THREAD

**Issue by xpirad** [XiaomiFirmwareUpdater/mi-firmware-updater#8]
Hi, i wonder if it's possible to include boot.img from miui?

Thanks!

**Comment by xpirad** [comment]
well, you know, these days we can flash gsi, so only system.img gets updated but kernel stays the same?

**Comment by yshalsager** [comment]
yeah it is @xpirad

**Comment by yshalsager** [comment]
I can't apply it generally, because most of the users don't use the stock kernel (it's always outdated).

**Comment by xpirad** [comment]
Okay, thanks.
